### ISSUE TITLE
Add a "copy" function for each code block

### ISSUE THREAD

**Issue by xy2z** [xy2z/PineDocs#155]
For each code block (`<pre><code>`) there should be added a "copy" icon in the top right position.
When you click the icon, it should copy the content of the code block.
Should also include a tooltip that says "Copy" on hover and then "Copied!" on click.

It should work exactly like this page: https://www.ngxs.io/recipes/authentication

![image](https://user-images.githubusercontent.com/4496997/135615114-3ac25f41-d077-479d-9226-3e9ea0c756e2.png)

Please use SVG for the icon

**Comment by Mylloon** [comment]
There is [highlightjs-copy](https://github.com/arronhunt/highlightjs-copy), it's possible to do it this way
