### ISSUE TITLE
CSS: Fix wiki theme content width

### ISSUE THREAD

**Issue by xy2z** [xy2z/PineDocs#19]
The 'wiki' theme isn't done
The content width should be 100% - and responsive

**Comment by sagarvd01** [comment]
do you have a url for a demo? if not, turn on github page for this repo

**Comment by emptyhand** [comment]
Hey! I'v created pull request for this issue:
https://github.com/xy2z/PineDocs/pull/21

**Comment by Cleanse** [comment]
#
