### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Mylloon** [xy2z/PineDocs#235]
Add a customizable css file for color-schemes and layouts for docker

In container:
- color-schemes/custom.css
- layouts/custom.css

And in host:
- config/custom-color-scheme.css
- config/custom-layout.css

with empty content?

**Comment by xy2z** [comment]
Yes I have had the same idea. I think one css file is enough, eg. `config/custom.css`  and then save it could be saved to public/css/custom.css
