### ISSUE TITLE
Add hidden folders

### ISSUE THREAD

**Issue by nasourso** [xy2z/PineDocs#81]
When creating a folder with a name like `.test` it should not be listed on the left side but should be accessible through a direct link.

**Comment by xy2z** [comment]
Can you give an example why you need this?

**Comment by nasourso** [comment]
For example, for a download directory. I have a download directory with many files in it and from there I just create direct download links. The only thing bothering me is the download folder showing up in the left menu.

But there are definitely more use cases. Just having the possibility to create (md) files which are not accessible through the main page would be fantastic.

**Comment by xy2z** [comment]
I see. Im just afraid some people would use this for excluding files without knowing the files are actually accessible. But maybe a big warning in the config file is sufficient.

The complete file tree will still be loaded in the html, for navigation to work, but will be hidden in the left side using css/js. Just so you know, everyone can still see what files there is, so this shouldnt be used for security reasons. Use exclude filter for that.

**Comment by xy2z** [comment]
How about a new option called `hide_folders_from_navigation` which can contain an array of folders to hide like

```yml
hide_folders_from_navigation:
  - hidden_dir
  - project/hide_this
```

**Comment by nasourso** [comment]
This is way better than my suggestion. I am looking forward to use this feature.
I really appreciate your efforts.

**Comment by xy2z** [comment]
Done in v1.1.5
https://github.com/xy2z/PineDocs/releases/tag/1.1.5
